src/main/java/recoder/single/bangle/member/controller/MemberController.java, src/main/webapp/WEB-INF/views/member/modifyForm.jsp, src/main/webapp/WEB-INF/views/member/signUpForm.jsp
=> 1월 10일 마지막 request

src/main/webapp/WEB-INF/views/index.jsp, src/main/webapp/WEB-INF/views/member/signUpForm.jsp, src/main/webapp/resources/css/index/index.css, src/main/webapp/resources/js/index/index.js
회원가입, 로그인, 마이페이지, 로그아웃 기능 작동 확인부탁드립니다~
=> 메인 화면 회원기능 수정

src/main/java/recoder/single/bangle/member/controller/MailController.java, src/main/webapp/WEB-INF/views/member/modifyForm.jsp, src/main/webapp/WEB-INF/views/member/signUpForm.jsp, src/main/webapp/resources/css/index/index.css
=> 오늘 마지막 리퀘스트~

src/main/webapp/WEB-INF/views/member/signUpForm.jsp, src/main/webapp/WEB-INF/web.xml
=> 회원가입 form 살짝 수정

pom.xml, src/main/java/recoder/single/bangle/hospital/controller/HospController.java, src/main/java/recoder/single/bangle/hospital/dto/HospCodeDTO.java, src/main/java/recoder/single/bangle/hospital/dto/HospDTO.java, src/main/java/recoder/single/bangle/hospital/service/HospService.java, src/main/java/recoder/single/bangle/member/controller/MailController.java, src/main/java/recoder/single/bangle/member/controller/MemberController.java, src/main/webapp/WEB-INF/views/hospital/hospList.jsp, src/main/webapp/WEB-INF/views/index.jsp
=> 병원 검색 기능 1차 완료!

src/main/webapp/WEB-INF/views/index.jsp, src/main/webapp/resources/js/index/index.js
=> 200117 sh 02 - index modify

src/main/webapp/WEB-INF/views/index.jsp, src/main/webapp/resources/css/index/index.css
=> index login box modify

src/main/webapp/WEB-INF/views/hospital/hospList.jsp, src/main/webapp/WEB-INF/views/member/modifyForm.jsp, src/main/webapp/WEB-INF/views/member/myInfo.jsp
=> 200119 sh 06 - hospital

src/main/webapp/WEB-INF/views/hospital/hospList.jsp, src/main/webapp/WEB-INF/views/member/login.jsp, src/main/webapp/WEB-INF/views/member/modifyForm.jsp, src/main/webapp/WEB-INF/views/member/modifyVerify.jsp, src/main/webapp/WEB-INF/views/member/myInfo.jsp, src/main/webapp/WEB-INF/views/member/myPage.jsp, src/main/webapp/WEB-INF/views/member/myScrapList.jsp, src/main/webapp/WEB-INF/views/member/signUpForm.jsp, src/main/webapp/WEB-INF/views/member/withdrawVerify.jsp
=> 200120 sh 01

src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
=> 200120 sh 02 - db name/password

src/main/java/recoder/single/bangle/member/DAO/MemberDAO.java, src/main/java/recoder/single/bangle/member/DTO/MemberDTO.java, src/main/java/recoder/single/bangle/member/controller/MailController.java, src/main/java/recoder/single/bangle/member/service/MemberService.java, src/main/java/recoder/single/bangle/restaurant/DAO/RestaurantDAO.java, src/main/java/recoder/single/bangle/restaurant/DAO/RestaurantFileDAO.java, src/main/java/recoder/single/bangle/restaurant/DTO/RestaurantDTO.java, src/main/java/recoder/single/bangle/restaurant/DTO/RestaurantFileDTO.java, src/main/java/recoder/single/bangle/restaurant/controller/RestaurantController.java, src/main/java/recoder/single/bangle/restaurant/service/RestaurantService.java, src/main/resources/mappers/member-mapper.xml, src/main/resources/mappers/restaurant-mapper.xml, src/main/resources/mappers/restaurantFile-mapper.xml, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, src/main/webapp/WEB-INF/views/hospital/hospList.jsp, src/main/webapp/WEB-INF/views/member/findIdResult.jsp, src/main/webapp/WEB-INF/views/member/findPw.jsp, src/main/webapp/WEB-INF/views/member/modifyForm.jsp, src/main/webapp/WEB-INF/views/member/myInfo.jsp, src/main/webapp/WEB-INF/views/member/signUpForm.jsp, src/main/webapp/WEB-INF/views/restaurant/rstDetail.jsp, src/main/webapp/WEB-INF/views/restaurant/rstList.jsp, src/main/webapp/WEB-INF/views/restaurant/rstWrite.jsp, src/main/webapp/WEB-INF/views/restaurant/rstWriteCheck.jsp
=> member, restaurant

src/main/java/recoder/single/bangle/member/controller/MailController.java, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
=> 200122 sh 01 - email

src/main/java/recoder/single/bangle/restaurant/DTO/RestaurantDTO.java, src/main/resources/mappers/restaurant-mapper.xml, src/main/webapp/WEB-INF/views/hospital/hospList.jsp, src/main/webapp/WEB-INF/views/restaurant/rstWrite.jsp
=> 200123 sh 01

src/main/java/recoder/single/bangle/restaurant/DAO/RestaurantDAO.java, src/main/java/recoder/single/bangle/restaurant/DTO/RestaurantDTO.java, src/main/java/recoder/single/bangle/restaurant/service/RestaurantService.java, src/main/resources/mappers/restaurant-mapper.xml, src/main/webapp/WEB-INF/views/restaurant/rstList.jsp, src/main/webapp/WEB-INF/views/restaurant/rstWrite.jsp
=> restaurant is updated

src/main/java/recoder/single/bangle/restaurant/DTO/RestaurantDTO.java, src/main/java/recoder/single/bangle/restaurant/controller/RestaurantController.java, src/main/webapp/WEB-INF/views/hospital/hospList.jsp, src/main/webapp/WEB-INF/views/restaurant/rstDetail.jsp, src/main/webapp/WEB-INF/views/restaurant/rstListN.jsp, src/main/webapp/WEB-INF/views/restaurant/rstListY.jsp, src/main/webapp/WEB-INF/views/restaurant/rstWrite.jsp
=> 200124 sh 02

src/main/java/recoder/single/bangle/member/controller/MailController.java, src/main/java/recoder/single/bangle/member/controller/MemberController.java, src/main/java/utils/EncryptionUtils.java, src/main/webapp/WEB-INF/views/hospital/hospList.jsp, src/main/webapp/WEB-INF/views/restaurant/rstListN.jsp, src/main/webapp/WEB-INF/views/restaurant/rstListY.jsp, src/main/webapp/WEB-INF/views/restaurant/rstWriteCheck.jsp
회원가입 / 비밀번호찾기 / 회원정보수정 / 회원탈퇴 할 때 비밀번호 암호화하기 기능 완료!
=> 200124 sh 03

src/main/webapp/WEB-INF/views/member/modifyForm.jsp, src/main/webapp/WEB-INF/views/member/modifyVerify.jsp, src/main/webapp/WEB-INF/views/member/myInfo.jsp, src/main/webapp/WEB-INF/views/member/myPage.jsp, src/main/webapp/WEB-INF/views/member/myScrapList.jsp, src/main/webapp/WEB-INF/views/member/withdrawVerify.jsp, src/main/webapp/WEB-INF/views/restaurant/rstDetail.jsp, src/main/webapp/WEB-INF/views/restaurant/rstListY.jsp
=> mypage is updated

src/main/webapp/resources/css/nav.css, src/main/webapp/resources/jsp/nav.jsp
우측 네비바 - 로그인 됐을 때 'Logout' 버튼에 text-decoration 남아있고 색깔 보라색으로 바뀌는 부분 수정
로그인 모달 창 - 로그인 됐을 때 아예 없어지도록 수정
=> 200125 sanghyun 01 - index nav is updated

src/main/java/recoder/single/bangle/member/controller/MailController.java, src/main/java/recoder/single/bangle/member/controller/MemberController.java, src/main/java/recoder/single/bangle/member/service/MemberService.java, src/main/java/recoder/single/bangle/restaurant/service/RestaurantService.java, src/main/java/utils/XSSprotect.java, src/main/webapp/WEB-INF/views/hospital/hospList.jsp, src/main/webapp/WEB-INF/views/member/modifyForm.jsp, src/main/webapp/WEB-INF/views/member/modifyVerify.jsp, src/main/webapp/WEB-INF/views/member/myInfo.jsp, src/main/webapp/WEB-INF/views/member/myPage.jsp, src/main/webapp/WEB-INF/views/member/signUpForm.jsp, src/main/webapp/WEB-INF/views/member/withdrawVerify.jsp, src/main/webapp/WEB-INF/views/restaurant/rstDetail.jsp, src/main/webapp/WEB-INF/views/restaurant/rstListN.jsp, src/main/webapp/WEB-INF/views/restaurant/rstListY.jsp, src/main/webapp/WEB-INF/views/restaurant/rstWrite.jsp, src/main/webapp/WEB-INF/views/restaurant/rstWriteCheck.jsp
=> xss protect

src/main/webapp/WEB-INF/views/member/myScrapList.jsp
=> 200127 sh 04 - scrap page

src/main/java/recoder/single/bangle/member/controller/MailController.java, src/main/java/recoder/single/bangle/restaurant/DAO/RestaurantDAO.java, src/main/java/recoder/single/bangle/restaurant/controller/RestaurantController.java, src/main/java/recoder/single/bangle/restaurant/service/RestaurantService.java, src/main/resources/mappers/restaurant-mapper.xml, src/main/webapp/WEB-INF/views/member/findId.jsp, src/main/webapp/WEB-INF/views/member/findPw.jsp, src/main/webapp/WEB-INF/views/member/modifyForm.jsp, src/main/webapp/WEB-INF/views/member/modifyVerify.jsp, src/main/webapp/WEB-INF/views/member/myInfo.jsp, src/main/webapp/WEB-INF/views/member/signUpForm.jsp, src/main/webapp/WEB-INF/views/member/withdrawVerify.jsp, src/main/webapp/WEB-INF/views/restaurant/rstApprovalCheck.jsp, src/main/webapp/WEB-INF/views/restaurant/rstDeleteCheck.jsp, src/main/webapp/WEB-INF/views/restaurant/rstDetail.jsp, src/main/webapp/WEB-INF/views/restaurant/rstListN.jsp
=> 200127 sanghyun - restaurant approval

src/main/webapp/WEB-INF/views/hospital/hospList.jsp, src/main/webapp/WEB-INF/views/member/findId.jsp, src/main/webapp/WEB-INF/views/member/findIdResult.jsp, src/main/webapp/WEB-INF/views/member/findPw.jsp, src/main/webapp/WEB-INF/views/member/findPwResult.jsp, src/main/webapp/WEB-INF/views/member/modifyForm.jsp, src/main/webapp/WEB-INF/views/member/modifyVerify.jsp, src/main/webapp/WEB-INF/views/member/myInfo.jsp, src/main/webapp/WEB-INF/views/member/myPage.jsp, src/main/webapp/WEB-INF/views/member/withdrawVerify.jsp, src/main/webapp/WEB-INF/views/restaurant/rstDetail.jsp, src/main/webapp/WEB-INF/views/restaurant/rstListY.jsp, src/main/webapp/WEB-INF/views/restaurant/rstWrite.jsp, src/main/webapp/resources/css/footer.css, src/main/webapp/resources/jsp/footer.jsp
마이페이지, 병원 검색, 식당 검색 모든 페이지에 footer 추가!
=> footer is applied

src/main/webapp/WEB-INF/views/index.jsp
=> 200128 sanghyun - index page footer

src/main/java/recoder/single/bangle/hospital/controller/HospController.java, src/main/java/recoder/single/bangle/member/controller/MailController.java, src/main/java/recoder/single/bangle/member/controller/MemberController.java, src/main/java/recoder/single/bangle/restaurant/controller/RestaurantController.java, src/main/webapp/WEB-INF/views/hospital/hospList.jsp, src/main/webapp/WEB-INF/views/restaurant/rstDetail.jsp, src/main/webapp/WEB-INF/views/restaurant/rstListY.jsp, src/main/webapp/WEB-INF/views/restaurant/rstWrite.jsp
return "redirect:/error";
추가함!
=> "to error page" is applied

src/main/webapp/WEB-INF/views/member/myPage.jsp, src/main/webapp/WEB-INF/views/member/myScrapList.jsp, src/main/webapp/WEB-INF/views/restaurant/rstListN.jsp, src/main/webapp/resources/css/footer.css
=> 200128 sanghyun - footer is modified

src/main/webapp/WEB-INF/views/index.jsp, src/main/webapp/WEB-INF/views/market/marketList.jsp, src/main/webapp/WEB-INF/views/market/marketdetail.jsp
=> 200128 sanghyun - index footer is modified

src/main/webapp/WEB-INF/views/member/signUpForm.jsp, src/main/webapp/WEB-INF/views/restaurant/rstWrite.jsp
회원가입시 주소 길이 제한
혼밥/혼술 글 작성시 제목 및 내용 길이 제한
=> 200128 sanghyun - regex

src/main/java/recoder/single/bangle/hospital/service/HospService.java, src/main/java/recoder/single/bangle/restaurant/controller/RestaurantController.java, src/main/webapp/WEB-INF/views/error.jsp, src/main/webapp/WEB-INF/views/restaurant/rstWrite.jsp
=> 200129 sanghyun - restaurant write

src/main/java/recoder/single/bangle/movie/controller/MovieController.java, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, src/main/webapp/WEB-INF/views/admin/hasReported.jsp, src/main/webapp/WEB-INF/views/member/myScrapList.jsp
=> 200129 sanghyun - movie

src/main/webapp/WEB-INF/views/market/marketdetail.jsp
=> 200129 sanghyun - remarket comments

src/main/webapp/WEB-INF/views/member/myScrapList.jsp, src/main/webapp/WEB-INF/views/tipBoard/detailView.jsp
=> kakao link
